### ISSUE TITLE
可以请教一下是如何打包的吗？

### ISSUE THREAD

**Issue by cyberxnomad** [jizai945/pyocd-exe#1]
我这边使用 pyOCD v0.33.1 的源码，打包后获取不到 USB 设备，但是直接运行 python 脚本又没问题。

**Comment by jizai945** [comment]
你好，我已经在项目中写了打包教程，欢迎查看

**Comment by jizai945** [comment]
> 我这边使用 pyOCD v0.33.1 的源码，打包后获取不到 USB 设备，但是直接运行 python 脚本又没问题。

你好我已经在工程中增加了打包教程，欢迎查看 @xray-bit

**Comment by cyberxnomad** [comment]
抱歉再次打扰，[教程.md](https://github.com/jizai945/pyocd-exe/blob/main/%E6%89%93%E5%8C%85%E6%95%99%E7%A8%8B/%E6%95%99%E7%A8%8B.md) 似乎是已加密文档，无法正常打开。

**Comment by jizai945** [comment]
> 



> 抱歉再次打扰，[教程.md](https://github.com/jizai945/pyocd-exe/blob/main/%E6%89%93%E5%8C%85%E6%95%99%E7%A8%8B/%E6%95%99%E7%A8%8B.md) 似乎是已加密文档，无法正常打开。

抱歉，我重新上传了。这次应该可以正常查看 @xray-bit

**Comment by cyberxnomad** [comment]
非常感谢！！
