### ISSUE TITLE
运行 .\pyocd.exe list -t 发现好多警告，是什么问题啊？

### ISSUE THREAD

**Issue by Guozhanxin** [jizai945/pyocd-exe#2]
.\pyocd.exe list -t

```
0000747 I Target type is cortex_m [board]
0000748 W unable to open builtin SVD file: [Errno 2] No such file or directory: 'C:\\Users\\11714\\AppData\\Local\\Temp\\_MEI121882\\pyocd\\debug\\svd\\svd_data.zip' [loader]
Traceback (most recent call last):
  File "pyocd\debug\svd\loader.py", line 34, in from_builtin
  File "pkg_resources\__init__.py", line 1136, in resource_stream
  File "pkg_resources\__init__.py", line 1385, in get_resource_stream
  File "pkg_resources\__init__.py", line 1388, in get_resource_string
  File "pkg_resources\__init__.py", line 1555, in _get
  File "PyInstaller\loader\pyimod03_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\11714\\AppData\\Local\\Temp\\_MEI121882\\pyocd\\debug\\svd\\svd_data.zip'
0000750 I Target type is cortex_m [board]
0000750 W unable to open builtin SVD file: [Errno 2] No such file or directory: 'C:\\Users\\11714\\AppData\\Local\\Temp\\_MEI121882\\pyocd\\debug\\svd\\svd_data.zip' [loader]
Traceback (most recent call last):
  File "pyocd\debug\svd\loader.py", line 34, in from_builtin
  File "pkg_resources\__init__.py", line 1136, in resource_stream
  File "pkg_resources\__init__.py", line 1385, in get_resource_stream
  File "pkg_resources\__init__.py", line 1388, in get_resource_string
  File "pkg_resources\__init__.py", line 1555, in _get
  File "PyInstaller\loader\pyimod03_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\11714\\AppData\\Local\\Temp\\_MEI121882\\pyocd\\debug\\svd\\svd_data.zip'
```

**Comment by jizai945** [comment]
> .\pyocd.exe list -t
> 
> ```
> 0000747 I Target type is cortex_m [board]
> 0000748 W unable to open builtin SVD file: [Errno 2] No such file or directory: 'C:\\Users\\11714\\AppData\\Local\\Temp\\_MEI121882\\pyocd\\debug\\svd\\svd_data.zip' [loader]
> Traceback (most recent call last):
>   File "pyocd\debug\svd\loader.py", line 34, in from_builtin
>   File "pkg_resources\__init__.py", line 1136, in resource_stream
>   File "pkg_resources\__init__.py", line 1385, in get_resource_stream
>   File "pkg_resources\__init__.py", line 1388, in get_resource_string
>   File "pkg_resources\__init__.py", line 1555, in _get
>   File "PyInstaller\loader\pyimod03_importers.py", line 344, in get_data
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\11714\\AppData\\Local\\Temp\\_MEI121882\\pyocd\\debug\\svd\\svd_data.zip'
> 0000750 I Target type is cortex_m [board]
> 0000750 W unable to open builtin SVD file: [Errno 2] No such file or directory: 'C:\\Users\\11714\\AppData\\Local\\Temp\\_MEI121882\\pyocd\\debug\\svd\\svd_data.zip' [loader]
> Traceback (most recent call last):
>   File "pyocd\debug\svd\loader.py", line 34, in from_builtin
>   File "pkg_resources\__init__.py", line 1136, in resource_stream
>   File "pkg_resources\__init__.py", line 1385, in get_resource_stream
>   File "pkg_resources\__init__.py", line 1388, in get_resource_string
>   File "pkg_resources\__init__.py", line 1555, in _get
>   File "PyInstaller\loader\pyimod03_importers.py", line 344, in get_data
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\11714\\AppData\\Local\\Temp\\_MEI121882\\pyocd\\debug\\svd\\svd_data.zip'
> ```

感谢你的反馈，我才发现这个问题，应该是我0.33.1这个版本打包中忘记了把svd文件打包进去，我重新打包上传了，应该没有这个问题了

**Comment by Guozhanxin** [comment]
如果按照仓库里的教程操作，会有这个问题吗😜

**Comment by jizai945** [comment]
> 

我刚刚就是按照教程的操作，重新打包了一份^.^
